# Generated by Django 6.0 on 2025-12-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('power', models.IntegerField()),
                ('level', models.IntegerField()),
                ('description', models.TextField()),
                ('rarity', models.CharField(max_length=50)),
            ],
        ),
    ]
